### ISSUE TITLE
Config file for exporter and inventory

### ISSUE THREAD

**Issue by viennaa** [sapcc/vrops-exporter#80]
FYI: I am currently looking into implementing a config file like this one. 
```yaml
---
user: default_username
password: default_password
port: 8080
debug: true
profiles:
  - description: "Example vROPS profile"
    matches:
      - '.*' # match vrops-name with a regex
    user: vrops_username
    password: vrops_password
    auth_source: Local
    datacenter_type: Datacenter
    
    # This one is just an idea, if someone wants to limit which metrics
    # to collect it could be configured like this
    filter:
      HostSystem:
        include: [ 'site1-*' ]
        exclude: [ '.*-secret' ]
```

I guess sooner or later people want/need to be able to configure how InventoryBuilder works.  The basic idea it to configure everything in profiles and match that with the dynamic vrops-instance-list from atlas. I think the most flexible  way to match profiles to vrops-instances is a regex on the name (any other ideas?)

I am planning on one configuration file for both services (inventory and exporter). I think this would be easier to implement and use. Are you OK with one file for both or separate files?

_Originally posted by @ThomasBuchinger in https://github.com/sapcc/vrops-exporter/pull/68#issuecomment-617732525_

**Comment by ThomasBuchinger** [comment]
Question: I guess we are waiting if richardtief is ok with it? Or do you see any problem with the proposal?

**Comment by viennaa** [comment]
Tbh I did not have time to really look into it, that's why there was no comment so far. My current thoughts on this:

We have a [kubernetes configfile](https://github.com/sapcc/helm-charts/blob/master/prometheus-exporters/vrops-exporter/values.yaml) which partially is providing what you want to add here.

We could reomve the first yaml layer ( `vrops:`) and then it would look ok. I would try to provide a file, which is usable from both sides: k8s and exporter/inventory.

What we would have in there now is the first part of your proposal:
```yaml
---
user: default_username
password: default_password
port: 8080
debug: true
```

We could also add a list of targets with different configurations under it like:
```yaml
vrops_targets:
  - target: testhost.foo
     username: vrops_username
     password:  vrops_password
     auth_source: Local
```

For the inventory part I like the idea of simply filtering them.
```yaml
  filter:
      HostSystem:
        include: [ 'site1-*' ]
        exclude: [ '.*-secret' ]
```

Since our approach is to keep vROps as dumb as possible, I would not go with vROps profiles.
